### ISSUE TITLE
Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher

### ISSUE THREAD

**Issue by litzbalane2017** [openponce/opencamera#1]
I have recently found this plugin to be useful in recording videos in flutter. However, I got the following errors when trying to run the plugin. 

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':open_camera' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

Here is my output for Flutter doctor: 

[✓] Flutter (Channel unknown, v1.10.6, on Linux, locale en_PH.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[✓] Connected device (1 available)

Thank you.

**Comment by diogoponce** [comment]
Problem solved. Update the application and if you have problems contact us.
