### ISSUE TITLE
version for the compile (1.0.0) and runtime (1.1.0)

### ISSUE THREAD

**Issue by hzp1993** [openponce/opencamera#2]
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'androidx.versionedparcelable:versionedparcelable' has different version for the compile (1.0.0) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

**Comment by diogoponce** [comment]
Problem solved. Update the application and if you have problems contact us.
