### ISSUE TITLE
Recording a video on Android Click and stop. Clicking the Back button will cause a memory leak.

### ISSUE THREAD

**Issue by hzp1993** [openponce/opencamera#3]
I/flutter (28784): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28784): The following assertion was thrown while finalizing the widget tree:
I/flutter (28784): _VideoPreviewState.dispose failed to call super.dispose.
I/flutter (28784): dispose() implementations must always call their superclass dispose() method, to ensure that all the
I/flutter (28784): resources used by the widget are fully released.

**Comment by diogoponce** [comment]
Problem solved. Update the application and if you have problems contact us.
