### ISSUE TITLE
Pod install will have problems

### ISSUE THREAD

**Issue by hzp1993** [openponce/opencamera#5]
[!] Unable to find a specification for `mobile-ffmpeg-https-gpl (= 4.2.2)` depended upon by `open_camera/https-gpl`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on

**Comment by diogoponce** [comment]
Hello! 
Try the following procedure and see if it works.

https://libraries.io/cocoapods/mobile-ffmpeg-https-gpl
